"""add raw_storage_path to filings

Revision ID: e4f94cc0d456
Revises: 378ebe020098
Create Date: 2026-09-28 08:26:34.162796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f94cc0d456'
down_revision: Union[str, Sequence[str], None] = '378ebe020098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('raw_storage_path', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'raw_storage_path')
    # ### end Alembic commands ###
